// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TypedTransBuffer.proto

package org.rtcs.rtcsroom.protocol;

public final class TypedTransBufferProto {
  private TypedTransBufferProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtcs_TypedTransBuffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rtcs_TypedTransBuffer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026TypedTransBuffer.proto\022\004rtcs\"j\n\020TypedT" +
      "ransBuffer\022\020\n\010fromuser\030\001 \001(\005\022\016\n\006touser\030\002" +
      " \001(\005\022\020\n\010pluginID\030\003 \001(\005\022\022\n\nbufferdata\030\004 \001" +
      "(\014\022\016\n\006roomid\030\005 \001(\tB8\n\032org.rtcs.rtcsroom." +
      "protocolB\025TypedTransBufferProtoP\001\370\001\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rtcs_TypedTransBuffer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rtcs_TypedTransBuffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rtcs_TypedTransBuffer_descriptor,
        new java.lang.String[] { "Fromuser", "Touser", "PluginID", "Bufferdata", "Roomid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
