// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TypedTransBuffer.proto

package org.rtcs.rtcsroom.protocol;

public interface TypedTransBufferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtcs.TypedTransBuffer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the message from which user
   * </pre>
   *
   * <code>int32 fromuser = 1;</code>
   */
  int getFromuser();

  /**
   * <pre>
   * the message to which user.
   * </pre>
   *
   * <code>int32 touser = 2;</code>
   */
  int getTouser();

  /**
   * <pre>
   * this message pluginID
   * </pre>
   *
   * <code>int32 pluginID = 3;</code>
   */
  int getPluginID();

  /**
   * <pre>
   * the trans buffer
   * </pre>
   *
   * <code>bytes bufferdata = 4;</code>
   */
  com.google.protobuf.ByteString getBufferdata();

  /**
   * <pre>
   * thie mssage to which room
   * </pre>
   *
   * <code>string roomid = 5;</code>
   */
  java.lang.String getRoomid();
  /**
   * <pre>
   * thie mssage to which room
   * </pre>
   *
   * <code>string roomid = 5;</code>
   */
  com.google.protobuf.ByteString
      getRoomidBytes();
}
