// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TypedTransBuffer.proto

package org.rtcs.rtcsroom.protocol;

/**
 * <pre>
 * A protocol buffer message type.
 * </pre>
 *
 * Protobuf type {@code rtcs.TypedTransBuffer}
 */
public  final class TypedTransBuffer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rtcs.TypedTransBuffer)
    TypedTransBufferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TypedTransBuffer.newBuilder() to construct.
  private TypedTransBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TypedTransBuffer() {
    fromuser_ = 0;
    touser_ = 0;
    pluginID_ = 0;
    bufferdata_ = com.google.protobuf.ByteString.EMPTY;
    roomid_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TypedTransBuffer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            fromuser_ = input.readInt32();
            break;
          }
          case 16: {

            touser_ = input.readInt32();
            break;
          }
          case 24: {

            pluginID_ = input.readInt32();
            break;
          }
          case 34: {

            bufferdata_ = input.readBytes();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            roomid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rtcs.rtcsroom.protocol.TypedTransBufferProto.internal_static_rtcs_TypedTransBuffer_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rtcs.rtcsroom.protocol.TypedTransBufferProto.internal_static_rtcs_TypedTransBuffer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rtcs.rtcsroom.protocol.TypedTransBuffer.class, org.rtcs.rtcsroom.protocol.TypedTransBuffer.Builder.class);
  }

  public static final int FROMUSER_FIELD_NUMBER = 1;
  private int fromuser_;
  /**
   * <pre>
   * the message from which user
   * </pre>
   *
   * <code>int32 fromuser = 1;</code>
   */
  public int getFromuser() {
    return fromuser_;
  }

  public static final int TOUSER_FIELD_NUMBER = 2;
  private int touser_;
  /**
   * <pre>
   * the message to which user.
   * </pre>
   *
   * <code>int32 touser = 2;</code>
   */
  public int getTouser() {
    return touser_;
  }

  public static final int PLUGINID_FIELD_NUMBER = 3;
  private int pluginID_;
  /**
   * <pre>
   * this message pluginID
   * </pre>
   *
   * <code>int32 pluginID = 3;</code>
   */
  public int getPluginID() {
    return pluginID_;
  }

  public static final int BUFFERDATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString bufferdata_;
  /**
   * <pre>
   * the trans buffer
   * </pre>
   *
   * <code>bytes bufferdata = 4;</code>
   */
  public com.google.protobuf.ByteString getBufferdata() {
    return bufferdata_;
  }

  public static final int ROOMID_FIELD_NUMBER = 5;
  private volatile java.lang.Object roomid_;
  /**
   * <pre>
   * thie mssage to which room
   * </pre>
   *
   * <code>string roomid = 5;</code>
   */
  public java.lang.String getRoomid() {
    java.lang.Object ref = roomid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * thie mssage to which room
   * </pre>
   *
   * <code>string roomid = 5;</code>
   */
  public com.google.protobuf.ByteString
      getRoomidBytes() {
    java.lang.Object ref = roomid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fromuser_ != 0) {
      output.writeInt32(1, fromuser_);
    }
    if (touser_ != 0) {
      output.writeInt32(2, touser_);
    }
    if (pluginID_ != 0) {
      output.writeInt32(3, pluginID_);
    }
    if (!bufferdata_.isEmpty()) {
      output.writeBytes(4, bufferdata_);
    }
    if (!getRoomidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, roomid_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fromuser_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, fromuser_);
    }
    if (touser_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, touser_);
    }
    if (pluginID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, pluginID_);
    }
    if (!bufferdata_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, bufferdata_);
    }
    if (!getRoomidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, roomid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rtcs.rtcsroom.protocol.TypedTransBuffer)) {
      return super.equals(obj);
    }
    org.rtcs.rtcsroom.protocol.TypedTransBuffer other = (org.rtcs.rtcsroom.protocol.TypedTransBuffer) obj;

    boolean result = true;
    result = result && (getFromuser()
        == other.getFromuser());
    result = result && (getTouser()
        == other.getTouser());
    result = result && (getPluginID()
        == other.getPluginID());
    result = result && getBufferdata()
        .equals(other.getBufferdata());
    result = result && getRoomid()
        .equals(other.getRoomid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROMUSER_FIELD_NUMBER;
    hash = (53 * hash) + getFromuser();
    hash = (37 * hash) + TOUSER_FIELD_NUMBER;
    hash = (53 * hash) + getTouser();
    hash = (37 * hash) + PLUGINID_FIELD_NUMBER;
    hash = (53 * hash) + getPluginID();
    hash = (37 * hash) + BUFFERDATA_FIELD_NUMBER;
    hash = (53 * hash) + getBufferdata().hashCode();
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rtcs.rtcsroom.protocol.TypedTransBuffer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A protocol buffer message type.
   * </pre>
   *
   * Protobuf type {@code rtcs.TypedTransBuffer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rtcs.TypedTransBuffer)
      org.rtcs.rtcsroom.protocol.TypedTransBufferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rtcs.rtcsroom.protocol.TypedTransBufferProto.internal_static_rtcs_TypedTransBuffer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rtcs.rtcsroom.protocol.TypedTransBufferProto.internal_static_rtcs_TypedTransBuffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rtcs.rtcsroom.protocol.TypedTransBuffer.class, org.rtcs.rtcsroom.protocol.TypedTransBuffer.Builder.class);
    }

    // Construct using org.rtcs.rtcsroom.protocol.TypedTransBuffer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      fromuser_ = 0;

      touser_ = 0;

      pluginID_ = 0;

      bufferdata_ = com.google.protobuf.ByteString.EMPTY;

      roomid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rtcs.rtcsroom.protocol.TypedTransBufferProto.internal_static_rtcs_TypedTransBuffer_descriptor;
    }

    public org.rtcs.rtcsroom.protocol.TypedTransBuffer getDefaultInstanceForType() {
      return org.rtcs.rtcsroom.protocol.TypedTransBuffer.getDefaultInstance();
    }

    public org.rtcs.rtcsroom.protocol.TypedTransBuffer build() {
      org.rtcs.rtcsroom.protocol.TypedTransBuffer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.rtcs.rtcsroom.protocol.TypedTransBuffer buildPartial() {
      org.rtcs.rtcsroom.protocol.TypedTransBuffer result = new org.rtcs.rtcsroom.protocol.TypedTransBuffer(this);
      result.fromuser_ = fromuser_;
      result.touser_ = touser_;
      result.pluginID_ = pluginID_;
      result.bufferdata_ = bufferdata_;
      result.roomid_ = roomid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rtcs.rtcsroom.protocol.TypedTransBuffer) {
        return mergeFrom((org.rtcs.rtcsroom.protocol.TypedTransBuffer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rtcs.rtcsroom.protocol.TypedTransBuffer other) {
      if (other == org.rtcs.rtcsroom.protocol.TypedTransBuffer.getDefaultInstance()) return this;
      if (other.getFromuser() != 0) {
        setFromuser(other.getFromuser());
      }
      if (other.getTouser() != 0) {
        setTouser(other.getTouser());
      }
      if (other.getPluginID() != 0) {
        setPluginID(other.getPluginID());
      }
      if (other.getBufferdata() != com.google.protobuf.ByteString.EMPTY) {
        setBufferdata(other.getBufferdata());
      }
      if (!other.getRoomid().isEmpty()) {
        roomid_ = other.roomid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rtcs.rtcsroom.protocol.TypedTransBuffer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rtcs.rtcsroom.protocol.TypedTransBuffer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int fromuser_ ;
    /**
     * <pre>
     * the message from which user
     * </pre>
     *
     * <code>int32 fromuser = 1;</code>
     */
    public int getFromuser() {
      return fromuser_;
    }
    /**
     * <pre>
     * the message from which user
     * </pre>
     *
     * <code>int32 fromuser = 1;</code>
     */
    public Builder setFromuser(int value) {
      
      fromuser_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the message from which user
     * </pre>
     *
     * <code>int32 fromuser = 1;</code>
     */
    public Builder clearFromuser() {
      
      fromuser_ = 0;
      onChanged();
      return this;
    }

    private int touser_ ;
    /**
     * <pre>
     * the message to which user.
     * </pre>
     *
     * <code>int32 touser = 2;</code>
     */
    public int getTouser() {
      return touser_;
    }
    /**
     * <pre>
     * the message to which user.
     * </pre>
     *
     * <code>int32 touser = 2;</code>
     */
    public Builder setTouser(int value) {
      
      touser_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the message to which user.
     * </pre>
     *
     * <code>int32 touser = 2;</code>
     */
    public Builder clearTouser() {
      
      touser_ = 0;
      onChanged();
      return this;
    }

    private int pluginID_ ;
    /**
     * <pre>
     * this message pluginID
     * </pre>
     *
     * <code>int32 pluginID = 3;</code>
     */
    public int getPluginID() {
      return pluginID_;
    }
    /**
     * <pre>
     * this message pluginID
     * </pre>
     *
     * <code>int32 pluginID = 3;</code>
     */
    public Builder setPluginID(int value) {
      
      pluginID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * this message pluginID
     * </pre>
     *
     * <code>int32 pluginID = 3;</code>
     */
    public Builder clearPluginID() {
      
      pluginID_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bufferdata_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * the trans buffer
     * </pre>
     *
     * <code>bytes bufferdata = 4;</code>
     */
    public com.google.protobuf.ByteString getBufferdata() {
      return bufferdata_;
    }
    /**
     * <pre>
     * the trans buffer
     * </pre>
     *
     * <code>bytes bufferdata = 4;</code>
     */
    public Builder setBufferdata(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bufferdata_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the trans buffer
     * </pre>
     *
     * <code>bytes bufferdata = 4;</code>
     */
    public Builder clearBufferdata() {
      
      bufferdata_ = getDefaultInstance().getBufferdata();
      onChanged();
      return this;
    }

    private java.lang.Object roomid_ = "";
    /**
     * <pre>
     * thie mssage to which room
     * </pre>
     *
     * <code>string roomid = 5;</code>
     */
    public java.lang.String getRoomid() {
      java.lang.Object ref = roomid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * thie mssage to which room
     * </pre>
     *
     * <code>string roomid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRoomidBytes() {
      java.lang.Object ref = roomid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * thie mssage to which room
     * </pre>
     *
     * <code>string roomid = 5;</code>
     */
    public Builder setRoomid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * thie mssage to which room
     * </pre>
     *
     * <code>string roomid = 5;</code>
     */
    public Builder clearRoomid() {
      
      roomid_ = getDefaultInstance().getRoomid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * thie mssage to which room
     * </pre>
     *
     * <code>string roomid = 5;</code>
     */
    public Builder setRoomidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rtcs.TypedTransBuffer)
  }

  // @@protoc_insertion_point(class_scope:rtcs.TypedTransBuffer)
  private static final org.rtcs.rtcsroom.protocol.TypedTransBuffer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rtcs.rtcsroom.protocol.TypedTransBuffer();
  }

  public static org.rtcs.rtcsroom.protocol.TypedTransBuffer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TypedTransBuffer>
      PARSER = new com.google.protobuf.AbstractParser<TypedTransBuffer>() {
    public TypedTransBuffer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TypedTransBuffer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TypedTransBuffer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TypedTransBuffer> getParserForType() {
    return PARSER;
  }

  public org.rtcs.rtcsroom.protocol.TypedTransBuffer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

